name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  library:
    name: macOS
    strategy:
      matrix:
        config: ['debug', 'release']
    runs-on: ios
    steps:
      - uses: actions/checkout@v4
      - name: Run ${{ matrix.config }} tests
        run: swift test -c ${{ matrix.config }}
      - name: Run compatibility tests
        run: make test-compatibility
        if: ${{ matrix.config == 'debug' }}
